### ISSUE TITLE
Workload : Pondération

### ISSUE THREAD

**Issue by maximewel** [HE-Arc/Caravel#153]
This issue follows a discussion with M.Mendes Reis about the weekly workload indicator that needs to be present in the monthly view (important for the final Caravel release).\
A ponderation should take place to ensure that a number of little works are considered as much workload as one big report (ex : 3 little homework might not be as challenging as making the final web dev delivery, P3 project, etc...)\
Some solutions have been mentionned : 
* Adding an "estimated workload" in hours (ex: Webdev should be 3*30h so 90h) to ponderate the workload by the estimated time of the project. This could be heavily skewed (profesors tend to underestimate, students could try to cheat the system by overestimating everything)
* Ponderating by the branch credits - dangerous, as the credits are not a good indicator in the current cursus
* Adding a way for the student to rate the workload of a particular project "on-the-fly"
    * This should be _very_ easy to do for students (as a matter of user expenrience). An idea has been evoked : having a little "reaction" board, akin to Discord, composed of 3 emojis - happy, neutral, stressed. These emojis represent a way for the student to declare if this particular project has an heavy toll on the week, and the app could use it to help ponderate the weekly workload. This proposition is just an example of an implementation giving a voice to the students while not requiring management and logistic time.
  
p-s : Good luck for your bachelor, you are awesome :-)

**Comment by grunenwald** [comment]
Thanks for your input !

I agree with your arguments. I would add that we don't expect Caravel to give a precise value for the workload, I think it would be a good step forward if it could give a trend indicator.

What about using more than one of your solutions ? 
* branch credits shouldn't be so bad : 1 credit worth 30h and for most branches half of this time should be autonomous work
* estimate the workload is a good exercise for the students for learning work time management. I think it's not a big problem if it's sometimes over or underrated : we will use it as an indicator, we don't expect an accurate value
* imho, emojis should be more accurate : a student can be happy working on a projet even if he spends more time on it (as you did for Caravel), and be stressed by a less time consuming project, when its motivation is lower... What about more emojis ? and/or emojis more expressive about the time spent on the projet (over/equals/under prof's expectations)

I think it would be nice to have a link somewhere with the expected workload in the module description : it's the only objective/official reference we can use as an argument in a discussion.

I agree 100% with @M4n0x when he says Caravel can't give a precise value, but only a trend that should trigger a discussion between students and profs. But I think 3 general emojis is a little poor.

Of course, any feedback should be facultative, at the good will of the students. I trust most of the students, and I think "cheating" in overestimate workload shouldn't be a big problem, as these values are only meant to trigger a discussion.

**Comment by M4n0x** [comment]
In my opinion the most common situations should require the least effort from the user (less is more). So when a situation is normal asking students to make inputs as estimating workload seems overkill to me : first of all because it's really hard to estimate as we are learning and most of the time it's new stuff and secondly because we are all differents, for some people it could take one hour while for some others it could take four. The other point is the fact that we have a lot of homework, if every student (if we want an average score) should estimate each homework it could take a lot of time. I would be ok with that if the indicator was very precise and the most usefull thing in the app but for what it takes and what we get I really think that's not worth it. 

As we have discussed previously, I think reactions is much relevant as an input when there is a problem, it requires less effort from the user and it really brings value to the information. Defining which reactions we should get is another topic (in which we need to dig a little 😄), I agree with the fact that only three reactions seems not enough. Maybe it will be a good idea to do a survey to get the most common problems students encounter in homework/project and adapt reactions from that view.

Regarding to the ECTS, I think it's also a good idea, each subject could have a new parameter ECTS. As we know the numbers of ECTS for each subject it'll be easy to create an indicator to show if a week seems overload or not. It requires almost no effort at all and can be very usefull to objectively balance workload.
